### ISSUE TITLE
Check password when inserting new version

### ISSUE THREAD

**Issue by tpetricek** [tpetricek/FsSnip.Website#38]
When inserting a new version of a password protected snippet, we should check the password first.

**Comment by avjgit** [comment]
Looks like this issue is solved. When I try to edit my password protected test snippet (http://fssnip.net/tr), I got "This snippet is protected by a password" message.

**Comment by tpetricek** [comment]
Sorry for the confusion!

The www.fssnip.net web site is still the old version. The new one (where this is not solved) is running here: http://fssnip.azurewebsites.net/
